# Generated by Django 4.2.7 on 2023-11-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('approved', 'Aprovado'), ('failed', 'Reprovado')], default='failed', max_length=10)),
                ('posture', models.CharField(choices=[('perfect', 'Perfeito'), ('good', 'Bom'), ('average', 'Médio'), ('poor', 'Ruim'), ('awful', 'Péssimo')], default='average', max_length=10)),
                ('date', models.DateField()),
                ('observations', models.TextField(max_length=500)),
            ],
        ),
    ]
