# Generated by Django 4.2.7 on 2023-11-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0001_initial'),
        ('daily_schedule', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetimeplaylist',
            name='responsible_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='freetimeplaylist',
            name='songs',
            field=models.ManyToManyField(related_name='%(class)s_playlists', to='songs.song'),
        ),
        migrations.AddField(
            model_name='classroomplaylist',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_playlists', to='daily_schedule.day'),
        ),
        migrations.AddField(
            model_name='classroomplaylist',
            name='responsible_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='classroomplaylist',
            name='songs',
            field=models.ManyToManyField(related_name='%(class)s_playlists', to='songs.song'),
        ),
    ]
