# Generated by Django 4.2.7 on 2023-11-04 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graduation', '0001_initial'),
        ('daily_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('day', models.CharField(choices=[('monday', 'Segunda'), ('tuesday', 'Terça'), ('wednesday', 'Quarta'), ('thursday', 'Quinta'), ('friday', 'Sexta'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10)),
                ('time', models.TimeField()),
                ('graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graduation.graduation')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, max_length=500)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('criteria', models.ManyToManyField(related_name='classroom_instances', to='graduation.criteria')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_instances', to='daily_schedule.day')),
            ],
        ),
    ]
